
package net.ddraig.suprememiningdimension.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.ddraig.suprememiningdimension.block.ZincOreBlock;
import net.ddraig.suprememiningdimension.block.ZincBlockBlock;
import net.ddraig.suprememiningdimension.block.YellowshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.YellowshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.YellowshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.YellowshroomCapBlock;
import net.ddraig.suprememiningdimension.block.WhiteshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.WhiteshroomCapBlock;
import net.ddraig.suprememiningdimension.block.UraniumOreBlock;
import net.ddraig.suprememiningdimension.block.UndergroundDimensionPortalBlock;
import net.ddraig.suprememiningdimension.block.TungstenOreBlock;
import net.ddraig.suprememiningdimension.block.TungstenBlockBlock;
import net.ddraig.suprememiningdimension.block.TinOreBlock;
import net.ddraig.suprememiningdimension.block.TinBlockBlock;
import net.ddraig.suprememiningdimension.block.SyeniteWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.SyeniteTilesBlock;
import net.ddraig.suprememiningdimension.block.SyeniteStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.SyeniteLargeTilesBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksCrackedBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledCrackedBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksChiseledBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBricksBlock;
import net.ddraig.suprememiningdimension.block.SyeniteBlock;
import net.ddraig.suprememiningdimension.block.SulphurOreBlock;
import net.ddraig.suprememiningdimension.block.StrangeForestsRuinedPortalBlock;
import net.ddraig.suprememiningdimension.block.StrangeForestsPortalBlock;
import net.ddraig.suprememiningdimension.block.SphaleriteOreBlock;
import net.ddraig.suprememiningdimension.block.SilverOreBlock;
import net.ddraig.suprememiningdimension.block.SilverBlockBlock;
import net.ddraig.suprememiningdimension.block.ShiftedSandsPortalBlock;
import net.ddraig.suprememiningdimension.block.ShadeStoneBlock;
import net.ddraig.suprememiningdimension.block.ShadeGrassBlock;
import net.ddraig.suprememiningdimension.block.ShadeDirtBlock;
import net.ddraig.suprememiningdimension.block.ShadeCobblestoneBlock;
import net.ddraig.suprememiningdimension.block.RelitLampBlock;
import net.ddraig.suprememiningdimension.block.QuartzOreBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapBlock;
import net.ddraig.suprememiningdimension.block.PlatinumOreBlock;
import net.ddraig.suprememiningdimension.block.PlatinumBlockBlock;
import net.ddraig.suprememiningdimension.block.PinkshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.PinkshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.PinkshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.PinkshroomCapBlock;
import net.ddraig.suprememiningdimension.block.OrangeshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.OrangeshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.OrangeshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.OrangeshroomCapBlock;
import net.ddraig.suprememiningdimension.block.OlivineSandBlock;
import net.ddraig.suprememiningdimension.block.NickelOreBlock;
import net.ddraig.suprememiningdimension.block.NickelBlockBlock;
import net.ddraig.suprememiningdimension.block.NetherIslesRuinedPortalBlock;
import net.ddraig.suprememiningdimension.block.NetherIslandPortalBlock;
import net.ddraig.suprememiningdimension.block.MusicStationBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkYellowPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkYellowPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkYellowGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkYellowBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkWhiteGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkWhiteBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkRedPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkRedPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkRedGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkRedBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurplePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurplePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurpleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurpleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkOrangePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkOrangePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkOrangeGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkOrangeBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBluePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBluePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlueGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlueBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackYellowPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackYellowPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackYellowGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackYellowBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackWhiteGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackWhiteBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackRedPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackRedPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackRedGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackRedBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurplePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurplePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurpleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurpleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangeGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangeBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkgreenPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkgreenPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanPaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBluePaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBluePaleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlueGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlueBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlock;
import net.ddraig.suprememiningdimension.block.MachinesifterBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksTopazBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksRubyBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksLapisBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksEmeraldBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksDiamondBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksBlock;
import net.ddraig.suprememiningdimension.block.LockedBricksAmethystBlock;
import net.ddraig.suprememiningdimension.block.LightObsidianBricksBlock;
import net.ddraig.suprememiningdimension.block.LeadOreBlock;
import net.ddraig.suprememiningdimension.block.LeadBlockBlock;
import net.ddraig.suprememiningdimension.block.IronReinforcedObsidianBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteTilesBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteLargeTilesBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksCrackedBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledCrackedBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksChiseledBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBricksBlock;
import net.ddraig.suprememiningdimension.block.IgnimbriteBlock;
import net.ddraig.suprememiningdimension.block.HoneyBlock;
import net.ddraig.suprememiningdimension.block.HeatedMagmaBlockBlock;
import net.ddraig.suprememiningdimension.block.GreyshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.GreyshroomCapBlock;
import net.ddraig.suprememiningdimension.block.GreenshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.GreenshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.GreenshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.GreenshroomCapBlock;
import net.ddraig.suprememiningdimension.block.GoldReinforcedObsidianBlock;
import net.ddraig.suprememiningdimension.block.GhostlyshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.GhostlyshroomCapBlock;
import net.ddraig.suprememiningdimension.block.GabbroWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.GabbroTilesBlock;
import net.ddraig.suprememiningdimension.block.GabbroStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesCrackedBlock;
import net.ddraig.suprememiningdimension.block.GabbroLargeTilesBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksCrackedBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledCrackedWallBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledCrackedStairsBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledCrackedSlabBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledCrackedBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksChiseledBlock;
import net.ddraig.suprememiningdimension.block.GabbroBricksBlock;
import net.ddraig.suprememiningdimension.block.GabbroBlock;
import net.ddraig.suprememiningdimension.block.FalseOverworldDimensionPortalBlock;
import net.ddraig.suprememiningdimension.block.ExtinguishedLampBlock;
import net.ddraig.suprememiningdimension.block.EtchedWoodBlock;
import net.ddraig.suprememiningdimension.block.EnderCavesPortalBlock;
import net.ddraig.suprememiningdimension.block.EndSoilBlock;
import net.ddraig.suprememiningdimension.block.EndGrassBlock;
import net.ddraig.suprememiningdimension.block.DiamondSandBlock;
import net.ddraig.suprememiningdimension.block.DiamondGravelBlock;
import net.ddraig.suprememiningdimension.block.DenseRedstoneOreBlock;
import net.ddraig.suprememiningdimension.block.DenseLapisOreBlock;
import net.ddraig.suprememiningdimension.block.DenseIronOreBlock;
import net.ddraig.suprememiningdimension.block.DenseGoldOreBlock;
import net.ddraig.suprememiningdimension.block.DenseEmeraldOreBlock;
import net.ddraig.suprememiningdimension.block.DenseDiamondOreBlock;
import net.ddraig.suprememiningdimension.block.DenseCopperOreBlock;
import net.ddraig.suprememiningdimension.block.DenseCoalOreBlock;
import net.ddraig.suprememiningdimension.block.DenseAndesiteBlock;
import net.ddraig.suprememiningdimension.block.DefinedVoidPortalBlock;
import net.ddraig.suprememiningdimension.block.DeepCavernsPortalBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapBlock;
import net.ddraig.suprememiningdimension.block.CrimsonshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.CrimsonshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.CrimsonshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.CrimsonshroomCapBlock;
import net.ddraig.suprememiningdimension.block.CobbledSyeniteWallBlock;
import net.ddraig.suprememiningdimension.block.CobbledSyeniteStairsBlock;
import net.ddraig.suprememiningdimension.block.CobbledSyeniteSlabBlock;
import net.ddraig.suprememiningdimension.block.CobbledSyeniteBlock;
import net.ddraig.suprememiningdimension.block.CobbledIgnimbriteWallBlock;
import net.ddraig.suprememiningdimension.block.CobbledIgnimbriteStairsBlock;
import net.ddraig.suprememiningdimension.block.CobbledIgnimbriteSlabBlock;
import net.ddraig.suprememiningdimension.block.CobbledIgnimbriteBlock;
import net.ddraig.suprememiningdimension.block.CobbledGabbroWallBlock;
import net.ddraig.suprememiningdimension.block.CobbledGabbroStairsBlock;
import net.ddraig.suprememiningdimension.block.CobbledGabbroSlabBlock;
import net.ddraig.suprememiningdimension.block.CobbledGabbroBlock;
import net.ddraig.suprememiningdimension.block.CobaltOreBlock;
import net.ddraig.suprememiningdimension.block.CobaltBlockBlock;
import net.ddraig.suprememiningdimension.block.CavernsPortalBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapPaleGlowingBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapPaleBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapBlock;
import net.ddraig.suprememiningdimension.block.BlockOfPeridotBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodWoodBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodStairsBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodSlabBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodSaplingBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodPressurePlateBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodPlanksBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodLogBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodLeavesBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodFenceGateBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodFenceBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodButtonBlock;
import net.ddraig.suprememiningdimension.block.BlackshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.BlackshroomCapBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalSolidBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalSmallBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalMediumBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalLargeBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalBuddingBlock;
import net.ddraig.suprememiningdimension.block.AugmentStationBlock;
import net.ddraig.suprememiningdimension.block.AntimonyOreBlock;
import net.ddraig.suprememiningdimension.block.AntimonyBlockBlock;
import net.ddraig.suprememiningdimension.block.AncientMossBlock;
import net.ddraig.suprememiningdimension.block.AmberSolidBlock;
import net.ddraig.suprememiningdimension.block.AmberBricksBlock;
import net.ddraig.suprememiningdimension.block.AluminumOreBlock;
import net.ddraig.suprememiningdimension.block.AluminumBlockBlock;
import net.ddraig.suprememiningdimension.SupremeMiningDimensionMod;

public class SupremeMiningDimensionModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, SupremeMiningDimensionMod.MODID);
	public static final RegistryObject<Block> IRON_REINFORCED_OBSIDIAN = REGISTRY.register("iron_reinforced_obsidian", () -> new IronReinforcedObsidianBlock());
	public static final RegistryObject<Block> GOLD_REINFORCED_OBSIDIAN = REGISTRY.register("gold_reinforced_obsidian", () -> new GoldReinforcedObsidianBlock());
	public static final RegistryObject<Block> LIGHT_OBSIDIAN_BRICKS = REGISTRY.register("light_obsidian_bricks", () -> new LightObsidianBricksBlock());
	public static final RegistryObject<Block> ETCHED_WOOD = REGISTRY.register("etched_wood", () -> new EtchedWoodBlock());
	public static final RegistryObject<Block> AMBER_BRICKS = REGISTRY.register("amber_bricks", () -> new AmberBricksBlock());
	public static final RegistryObject<Block> HEATED_MAGMA_BLOCK = REGISTRY.register("heated_magma_block", () -> new HeatedMagmaBlockBlock());
	public static final RegistryObject<Block> FALSE_OVERWORLD_DIMENSION_PORTAL = REGISTRY.register("false_overworld_dimension_portal", () -> new FalseOverworldDimensionPortalBlock());
	public static final RegistryObject<Block> NETHER_ISLAND_PORTAL = REGISTRY.register("nether_island_portal", () -> new NetherIslandPortalBlock());
	public static final RegistryObject<Block> UNDERGROUND_DIMENSION_PORTAL = REGISTRY.register("underground_dimension_portal", () -> new UndergroundDimensionPortalBlock());
	public static final RegistryObject<Block> CAVERNS_PORTAL = REGISTRY.register("caverns_portal", () -> new CavernsPortalBlock());
	public static final RegistryObject<Block> DEEP_CAVERNS_PORTAL = REGISTRY.register("deep_caverns_portal", () -> new DeepCavernsPortalBlock());
	public static final RegistryObject<Block> ENDER_CAVES_PORTAL = REGISTRY.register("ender_caves_portal", () -> new EnderCavesPortalBlock());
	public static final RegistryObject<Block> STRANGE_FORESTS_PORTAL = REGISTRY.register("strange_forests_portal", () -> new StrangeForestsPortalBlock());
	public static final RegistryObject<Block> SHIFTED_SANDS_PORTAL = REGISTRY.register("shifted_sands_portal", () -> new ShiftedSandsPortalBlock());
	public static final RegistryObject<Block> DENSE_DIAMOND_ORE = REGISTRY.register("dense_diamond_ore", () -> new DenseDiamondOreBlock());
	public static final RegistryObject<Block> DENSE_IRON_ORE = REGISTRY.register("dense_iron_ore", () -> new DenseIronOreBlock());
	public static final RegistryObject<Block> DENSE_REDSTONE_ORE = REGISTRY.register("dense_redstone_ore", () -> new DenseRedstoneOreBlock());
	public static final RegistryObject<Block> DENSE_COPPER_ORE = REGISTRY.register("dense_copper_ore", () -> new DenseCopperOreBlock());
	public static final RegistryObject<Block> DENSE_COAL_ORE = REGISTRY.register("dense_coal_ore", () -> new DenseCoalOreBlock());
	public static final RegistryObject<Block> QUARTZ_ORE = REGISTRY.register("quartz_ore", () -> new QuartzOreBlock());
	public static final RegistryObject<Block> DENSE_LAPIS_ORE = REGISTRY.register("dense_lapis_ore", () -> new DenseLapisOreBlock());
	public static final RegistryObject<Block> DENSE_GOLD_ORE = REGISTRY.register("dense_gold_ore", () -> new DenseGoldOreBlock());
	public static final RegistryObject<Block> EXTINGUISHED_LAMP = REGISTRY.register("extinguished_lamp", () -> new ExtinguishedLampBlock());
	public static final RegistryObject<Block> RELIT_LAMP = REGISTRY.register("relit_lamp", () -> new RelitLampBlock());
	public static final RegistryObject<Block> DENSE_EMERALD_ORE = REGISTRY.register("dense_emerald_ore", () -> new DenseEmeraldOreBlock());
	public static final RegistryObject<Block> SILVER_ORE = REGISTRY.register("silver_ore", () -> new SilverOreBlock());
	public static final RegistryObject<Block> SILVER_BLOCK = REGISTRY.register("silver_block", () -> new SilverBlockBlock());
	public static final RegistryObject<Block> TIN_ORE = REGISTRY.register("tin_ore", () -> new TinOreBlock());
	public static final RegistryObject<Block> TIN_BLOCK = REGISTRY.register("tin_block", () -> new TinBlockBlock());
	public static final RegistryObject<Block> TUNGSTEN_ORE = REGISTRY.register("tungsten_ore", () -> new TungstenOreBlock());
	public static final RegistryObject<Block> TUNGSTEN_BLOCK = REGISTRY.register("tungsten_block", () -> new TungstenBlockBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> LEAD_BLOCK = REGISTRY.register("lead_block", () -> new LeadBlockBlock());
	public static final RegistryObject<Block> DENSE_ANDESITE = REGISTRY.register("dense_andesite", () -> new DenseAndesiteBlock());
	public static final RegistryObject<Block> NICKEL_ORE = REGISTRY.register("nickel_ore", () -> new NickelOreBlock());
	public static final RegistryObject<Block> NICKEL_BLOCK = REGISTRY.register("nickel_block", () -> new NickelBlockBlock());
	public static final RegistryObject<Block> PLATINUM_ORE = REGISTRY.register("platinum_ore", () -> new PlatinumOreBlock());
	public static final RegistryObject<Block> PLATINUM_BLOCK = REGISTRY.register("platinum_block", () -> new PlatinumBlockBlock());
	public static final RegistryObject<Block> ALUMINUM_ORE = REGISTRY.register("aluminum_ore", () -> new AluminumOreBlock());
	public static final RegistryObject<Block> ALUMINUM_BLOCK = REGISTRY.register("aluminum_block", () -> new AluminumBlockBlock());
	public static final RegistryObject<Block> ZINC_ORE = REGISTRY.register("zinc_ore", () -> new ZincOreBlock());
	public static final RegistryObject<Block> ZINC_BLOCK = REGISTRY.register("zinc_block", () -> new ZincBlockBlock());
	public static final RegistryObject<Block> SULPHUR_ORE = REGISTRY.register("sulphur_ore", () -> new SulphurOreBlock());
	public static final RegistryObject<Block> ANTIMONY_ORE = REGISTRY.register("antimony_ore", () -> new AntimonyOreBlock());
	public static final RegistryObject<Block> ANTIMONY_BLOCK = REGISTRY.register("antimony_block", () -> new AntimonyBlockBlock());
	public static final RegistryObject<Block> COBALT_ORE = REGISTRY.register("cobalt_ore", () -> new CobaltOreBlock());
	public static final RegistryObject<Block> COBALT_BLOCK = REGISTRY.register("cobalt_block", () -> new CobaltBlockBlock());
	public static final RegistryObject<Block> SPHALERITE_ORE = REGISTRY.register("sphalerite_ore", () -> new SphaleriteOreBlock());
	public static final RegistryObject<Block> DIAMOND_SAND = REGISTRY.register("diamond_sand", () -> new DiamondSandBlock());
	public static final RegistryObject<Block> DIAMOND_GRAVEL = REGISTRY.register("diamond_gravel", () -> new DiamondGravelBlock());
	public static final RegistryObject<Block> AMBER_SOLID = REGISTRY.register("amber_solid", () -> new AmberSolidBlock());
	public static final RegistryObject<Block> OLIVINE_SAND = REGISTRY.register("olivine_sand", () -> new OlivineSandBlock());
	public static final RegistryObject<Block> MACHINESIFTER = REGISTRY.register("machinesifter", () -> new MachinesifterBlock());
	public static final RegistryObject<Block> BLOCK_OF_PERIDOT = REGISTRY.register("block_of_peridot", () -> new BlockOfPeridotBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP = REGISTRY.register("blueshroom_cap", () -> new BlueshroomCapBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP_PALE = REGISTRY.register("blueshroom_cap_pale", () -> new BlueshroomCapPaleBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP_GLOWING = REGISTRY.register("blueshroom_cap_glowing", () -> new BlueshroomCapGlowingBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP_PALE_GLOWING = REGISTRY.register("blueshroom_cap_pale_glowing", () -> new BlueshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP = REGISTRY.register("cyanshroom_cap", () -> new CyanshroomCapBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP_PALE = REGISTRY.register("cyanshroom_cap_pale", () -> new CyanshroomCapPaleBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP_GLOWING = REGISTRY.register("cyanshroom_cap_glowing", () -> new CyanshroomCapGlowingBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP_PALE_GLOWING = REGISTRY.register("cyanshroom_cap_pale_glowing", () -> new CyanshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> GREYSHROOM_CAP = REGISTRY.register("greyshroom_cap", () -> new GreyshroomCapBlock());
	public static final RegistryObject<Block> GREYSHROOM_CAP_GLOWING = REGISTRY.register("greyshroom_cap_glowing", () -> new GreyshroomCapGlowingBlock());
	public static final RegistryObject<Block> GHOSTLYSHROOM_CAP = REGISTRY.register("ghostlyshroom_cap", () -> new GhostlyshroomCapBlock());
	public static final RegistryObject<Block> GHOSTLYSHROOM_CAP_GLOWING = REGISTRY.register("ghostlyshroom_cap_glowing", () -> new GhostlyshroomCapGlowingBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP = REGISTRY.register("purpleshroom_cap", () -> new PurpleshroomCapBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP_PALE = REGISTRY.register("purpleshroom_cap_pale", () -> new PurpleshroomCapPaleBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP_GLOWING = REGISTRY.register("purpleshroom_cap_glowing", () -> new PurpleshroomCapGlowingBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP_PALE_GLOWING = REGISTRY.register("purpleshroom_cap_pale_glowing", () -> new PurpleshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> PINKSHROOM_CAP = REGISTRY.register("pinkshroom_cap", () -> new PinkshroomCapBlock());
	public static final RegistryObject<Block> PINKSHROOM_CAP_PALE = REGISTRY.register("pinkshroom_cap_pale", () -> new PinkshroomCapPaleBlock());
	public static final RegistryObject<Block> PINKSHROOM_CAP_GLOWING = REGISTRY.register("pinkshroom_cap_glowing", () -> new PinkshroomCapGlowingBlock());
	public static final RegistryObject<Block> PINKSHROOM_CAP_PALE_GLOWING = REGISTRY.register("pinkshroom_cap_pale_glowing", () -> new PinkshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> GREENSHROOM_CAP = REGISTRY.register("greenshroom_cap", () -> new GreenshroomCapBlock());
	public static final RegistryObject<Block> GREENSHROOM_CAP_PALE = REGISTRY.register("greenshroom_cap_pale", () -> new GreenshroomCapPaleBlock());
	public static final RegistryObject<Block> GREENSHROOM_CAP_GLOWING = REGISTRY.register("greenshroom_cap_glowing", () -> new GreenshroomCapGlowingBlock());
	public static final RegistryObject<Block> GREENSHROOM_CAP_PALE_GLOWING = REGISTRY.register("greenshroom_cap_pale_glowing", () -> new GreenshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> YELLOWSHROOM_CAP = REGISTRY.register("yellowshroom_cap", () -> new YellowshroomCapBlock());
	public static final RegistryObject<Block> YELLOWSHROOM_CAP_PALE = REGISTRY.register("yellowshroom_cap_pale", () -> new YellowshroomCapPaleBlock());
	public static final RegistryObject<Block> YELLOWSHROOM_CAP_GLOWING = REGISTRY.register("yellowshroom_cap_glowing", () -> new YellowshroomCapGlowingBlock());
	public static final RegistryObject<Block> YELLOWSHROOM_CAP_PALE_GLOWING = REGISTRY.register("yellowshroom_cap_pale_glowing", () -> new YellowshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> ORANGESHROOM_CAP = REGISTRY.register("orangeshroom_cap", () -> new OrangeshroomCapBlock());
	public static final RegistryObject<Block> ORANGESHROOM_CAP_PALE = REGISTRY.register("orangeshroom_cap_pale", () -> new OrangeshroomCapPaleBlock());
	public static final RegistryObject<Block> ORANGESHROOM_CAP_GLOWING = REGISTRY.register("orangeshroom_cap_glowing", () -> new OrangeshroomCapGlowingBlock());
	public static final RegistryObject<Block> ORANGESHROOM_CAP_PALE_GLOWING = REGISTRY.register("orangeshroom_cap_pale_glowing", () -> new OrangeshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> CRIMSONSHROOM_CAP = REGISTRY.register("crimsonshroom_cap", () -> new CrimsonshroomCapBlock());
	public static final RegistryObject<Block> CRIMSONSHROOM_CAP_PALE = REGISTRY.register("crimsonshroom_cap_pale", () -> new CrimsonshroomCapPaleBlock());
	public static final RegistryObject<Block> CRIMSONSHROOM_CAP_GLOWING = REGISTRY.register("crimsonshroom_cap_glowing", () -> new CrimsonshroomCapGlowingBlock());
	public static final RegistryObject<Block> CRIMSONSHROOM_CAP_PALE_GLOWING = REGISTRY.register("crimsonshroom_cap_pale_glowing", () -> new CrimsonshroomCapPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE = REGISTRY.register("mushroom_stalk_blue", () -> new MushroomStalkBlueBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE_PALE = REGISTRY.register("mushroom_stalk_blue_pale", () -> new MushroomStalkBluePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE_GLOWING = REGISTRY.register("mushroom_stalk_blue_glowing", () -> new MushroomStalkBlueGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_blue_pale_glowing", () -> new MushroomStalkBluePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN = REGISTRY.register("mushroom_stalk_cyan", () -> new MushroomStalkCyanBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN_PALE = REGISTRY.register("mushroom_stalk_cyan_pale", () -> new MushroomStalkCyanPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN_GLOWING = REGISTRY.register("mushroom_stalk_cyan_glowing", () -> new MushroomStalkCyanGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN_PALE_GLOWING = REGISTRY.register("mushroom_stalk_cyan_pale_glowing", () -> new MushroomStalkCyanPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN = REGISTRY.register("mushroom_stalk_green", () -> new MushroomStalkGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN_PALE = REGISTRY.register("mushroom_stalk_green_pale", () -> new MushroomStalkGreenPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_green_glowing", () -> new MushroomStalkGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN_PALE_GLOWING = REGISTRY.register("mushroom_stalk_green_pale_glowing", () -> new MushroomStalkGreenPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE = REGISTRY.register("mushroom_stalk_purple", () -> new MushroomStalkPurpleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE_PALE = REGISTRY.register("mushroom_stalk_purple_pale", () -> new MushroomStalkPurplePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE_GLOWING = REGISTRY.register("mushroom_stalk_purple_glowing", () -> new MushroomStalkPurpleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_purple_pale_glowing", () -> new MushroomStalkPurplePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_YELLOW = REGISTRY.register("mushroom_stalk_yellow", () -> new MushroomStalkYellowBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_YELLOW_PALE = REGISTRY.register("mushroom_stalk_yellow_pale", () -> new MushroomStalkYellowPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_YELLOW_GLOWING = REGISTRY.register("mushroom_stalk_yellow_glowing", () -> new MushroomStalkYellowGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_YELLOW_PALE_GLOWING = REGISTRY.register("mushroom_stalk_yellow_pale_glowing", () -> new MushroomStalkYellowPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_ORANGE = REGISTRY.register("mushroom_stalk_orange", () -> new MushroomStalkOrangeBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_ORANGE_PALE = REGISTRY.register("mushroom_stalk_orange_pale", () -> new MushroomStalkOrangePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_ORANGE_GLOWING = REGISTRY.register("mushroom_stalk_orange_glowing", () -> new MushroomStalkOrangeGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_ORANGE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_orange_pale_glowing", () -> new MushroomStalkOrangePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_RED = REGISTRY.register("mushroom_stalk_red", () -> new MushroomStalkRedBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_RED_PALE = REGISTRY.register("mushroom_stalk_red_pale", () -> new MushroomStalkRedPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_RED_GLOWING = REGISTRY.register("mushroom_stalk_red_glowing", () -> new MushroomStalkRedGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_RED_PALE_GLOWING = REGISTRY.register("mushroom_stalk_red_pale_glowing", () -> new MushroomStalkRedPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_WHITE = REGISTRY.register("mushroom_stalk_white", () -> new MushroomStalkWhiteBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_WHITE_GLOWING = REGISTRY.register("mushroom_stalk_white_glowing", () -> new MushroomStalkWhiteGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK = REGISTRY.register("mushroom_stalk_black", () -> new MushroomStalkBlackBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PALE = REGISTRY.register("mushroom_stalk_black_pale", () -> new MushroomStalkBlackPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GLOWING = REGISTRY.register("mushroom_stalk_black_glowing", () -> new MushroomStalkBlackGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_pale_glowing", () -> new MushroomStalkBlackPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE = REGISTRY.register("mushroom_stalk_black_blue", () -> new MushroomStalkBlackBlueBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE_PALE = REGISTRY.register("mushroom_stalk_black_blue_pale", () -> new MushroomStalkBlackBluePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE_GLOWING = REGISTRY.register("mushroom_stalk_black_blue_glowing", () -> new MushroomStalkBlackBlueGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_blue_pale_glowing", () -> new MushroomStalkBlackBluePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN = REGISTRY.register("mushroom_stalk_black_cyan", () -> new MushroomStalkBlackCyanBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN_PALE = REGISTRY.register("mushroom_stalk_black_cyan_pale", () -> new MushroomStalkBlackCyanPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN_GLOWING = REGISTRY.register("mushroom_stalk_black_cyan_glowing", () -> new MushroomStalkBlackCyanGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_cyan_pale_glowing", () -> new MushroomStalkBlackCyanPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARK_GREEN = REGISTRY.register("mushroom_stalk_black_dark_green", () -> new MushroomStalkBlackDarkGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARKGREEN_PALE = REGISTRY.register("mushroom_stalk_black_darkgreen_pale", () -> new MushroomStalkBlackDarkgreenPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_black_dark_green_glowing", () -> new MushroomStalkBlackDarkGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARKGREEN_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_darkgreen_pale_glowing", () -> new MushroomStalkBlackDarkgreenPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN = REGISTRY.register("mushroom_stalk_black_green", () -> new MushroomStalkBlackGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN_PALE = REGISTRY.register("mushroom_stalk_black_green_pale", () -> new MushroomStalkBlackGreenPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_black_green_glowing", () -> new MushroomStalkBlackGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_green_pale_glowing", () -> new MushroomStalkBlackGreenPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE = REGISTRY.register("mushroom_stalk_black_purple", () -> new MushroomStalkBlackPurpleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE_PALE = REGISTRY.register("mushroom_stalk_black_purple_pale", () -> new MushroomStalkBlackPurplePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE_GLOWING = REGISTRY.register("mushroom_stalk_black_purple_glowing", () -> new MushroomStalkBlackPurpleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_purple_pale_glowing", () -> new MushroomStalkBlackPurplePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_YELLOW = REGISTRY.register("mushroom_stalk_black_yellow", () -> new MushroomStalkBlackYellowBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_YELLOW_PALE = REGISTRY.register("mushroom_stalk_black_yellow_pale", () -> new MushroomStalkBlackYellowPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_YELLOW_GLOWING = REGISTRY.register("mushroom_stalk_black_yellow_glowing", () -> new MushroomStalkBlackYellowGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_YELLOW_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_yellow_pale_glowing", () -> new MushroomStalkBlackYellowPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE = REGISTRY.register("mushroom_stalk_black_orange", () -> new MushroomStalkBlackOrangeBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE_PALE = REGISTRY.register("mushroom_stalk_black_orange_pale", () -> new MushroomStalkBlackOrangePaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE_GLOWING = REGISTRY.register("mushroom_stalk_black_orange_glowing", () -> new MushroomStalkBlackOrangeGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_orange_pale_glowing", () -> new MushroomStalkBlackOrangePaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_RED = REGISTRY.register("mushroom_stalk_black_red", () -> new MushroomStalkBlackRedBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_RED_PALE = REGISTRY.register("mushroom_stalk_black_red_pale", () -> new MushroomStalkBlackRedPaleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_RED_GLOWING = REGISTRY.register("mushroom_stalk_black_red_glowing", () -> new MushroomStalkBlackRedGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_RED_PALE_GLOWING = REGISTRY.register("mushroom_stalk_black_red_pale_glowing", () -> new MushroomStalkBlackRedPaleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_WHITE = REGISTRY.register("mushroom_stalk_black_white", () -> new MushroomStalkBlackWhiteBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_WHITE_GLOWING = REGISTRY.register("mushroom_stalk_black_white_glowing", () -> new MushroomStalkBlackWhiteGlowingBlock());
	public static final RegistryObject<Block> HONEY = REGISTRY.register("honey", () -> new HoneyBlock());
	public static final RegistryObject<Block> MUSIC_STATION = REGISTRY.register("music_station", () -> new MusicStationBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_SMALL = REGISTRY.register("benitoite_crystal_small", () -> new BenitoiteCrystalSmallBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_MEDIUM = REGISTRY.register("benitoite_crystal_medium", () -> new BenitoiteCrystalMediumBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_LARGE = REGISTRY.register("benitoite_crystal_large", () -> new BenitoiteCrystalLargeBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_SOLID = REGISTRY.register("benitoite_crystal_solid", () -> new BenitoiteCrystalSolidBlock());
	public static final RegistryObject<Block> SHADE_COBBLESTONE = REGISTRY.register("shade_cobblestone", () -> new ShadeCobblestoneBlock());
	public static final RegistryObject<Block> SHADE_STONE = REGISTRY.register("shade_stone", () -> new ShadeStoneBlock());
	public static final RegistryObject<Block> SHADE_DIRT = REGISTRY.register("shade_dirt", () -> new ShadeDirtBlock());
	public static final RegistryObject<Block> SHADE_GRASS = REGISTRY.register("shade_grass", () -> new ShadeGrassBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_BUDDING = REGISTRY.register("benitoite_crystal_budding", () -> new BenitoiteCrystalBuddingBlock());
	public static final RegistryObject<Block> ANCIENT_MOSS = REGISTRY.register("ancient_moss", () -> new AncientMossBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_WOOD = REGISTRY.register("blightwood_wood", () -> new BlightwoodWoodBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_LOG = REGISTRY.register("blightwood_log", () -> new BlightwoodLogBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_PLANKS = REGISTRY.register("blightwood_planks", () -> new BlightwoodPlanksBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_LEAVES = REGISTRY.register("blightwood_leaves", () -> new BlightwoodLeavesBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_STAIRS = REGISTRY.register("blightwood_stairs", () -> new BlightwoodStairsBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_SLAB = REGISTRY.register("blightwood_slab", () -> new BlightwoodSlabBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_FENCE = REGISTRY.register("blightwood_fence", () -> new BlightwoodFenceBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_FENCE_GATE = REGISTRY.register("blightwood_fence_gate", () -> new BlightwoodFenceGateBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_PRESSURE_PLATE = REGISTRY.register("blightwood_pressure_plate", () -> new BlightwoodPressurePlateBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_BUTTON = REGISTRY.register("blightwood_button", () -> new BlightwoodButtonBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_SAPLING = REGISTRY.register("blightwood_sapling", () -> new BlightwoodSaplingBlock());
	public static final RegistryObject<Block> END_SOIL = REGISTRY.register("end_soil", () -> new EndSoilBlock());
	public static final RegistryObject<Block> END_GRASS = REGISTRY.register("end_grass", () -> new EndGrassBlock());
	public static final RegistryObject<Block> STRANGE_FORESTS_RUINED_PORTAL = REGISTRY.register("strange_forests_ruined_portal", () -> new StrangeForestsRuinedPortalBlock());
	public static final RegistryObject<Block> GABBRO = REGISTRY.register("gabbro", () -> new GabbroBlock());
	public static final RegistryObject<Block> COBBLED_GABBRO = REGISTRY.register("cobbled_gabbro", () -> new CobbledGabbroBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS = REGISTRY.register("gabbro_bricks", () -> new GabbroBricksBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CRACKED = REGISTRY.register("gabbro_bricks_cracked", () -> new GabbroBricksCrackedBlock());
	public static final RegistryObject<Block> GABBRO_TILES = REGISTRY.register("gabbro_tiles", () -> new GabbroTilesBlock());
	public static final RegistryObject<Block> GABBRO_TILES_CRACKED = REGISTRY.register("gabbro_tiles_cracked", () -> new GabbroTilesCrackedBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES = REGISTRY.register("gabbro_large_tiles", () -> new GabbroLargeTilesBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_CRACKED = REGISTRY.register("gabbro_large_tiles_cracked", () -> new GabbroLargeTilesCrackedBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED = REGISTRY.register("gabbro_bricks_chiseled", () -> new GabbroBricksChiseledBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_CRACKED = REGISTRY.register("gabbro_bricks_chiseled_cracked", () -> new GabbroBricksChiseledCrackedBlock());
	public static final RegistryObject<Block> GABBRO_WALL = REGISTRY.register("gabbro_wall", () -> new GabbroWallBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_WALL = REGISTRY.register("gabbro_bricks_wall", () -> new GabbroBricksWallBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CRACKED_WALL = REGISTRY.register("gabbro_bricks_cracked_wall", () -> new GabbroBricksCrackedWallBlock());
	public static final RegistryObject<Block> GABBRO_TILES_WALL = REGISTRY.register("gabbro_tiles_wall", () -> new GabbroTilesWallBlock());
	public static final RegistryObject<Block> GABBRO_TILES_CRACKED_WALL = REGISTRY.register("gabbro_tiles_cracked_wall", () -> new GabbroTilesCrackedWallBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_WALL = REGISTRY.register("gabbro_large_tiles_wall", () -> new GabbroLargeTilesWallBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_CRACKED_WALL = REGISTRY.register("gabbro_large_tiles_cracked_wall", () -> new GabbroLargeTilesCrackedWallBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_WALL = REGISTRY.register("gabbro_bricks_chiseled_wall", () -> new GabbroBricksChiseledWallBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_CRACKED_WALL = REGISTRY.register("gabbro_bricks_chiseled_cracked_wall", () -> new GabbroBricksChiseledCrackedWallBlock());
	public static final RegistryObject<Block> COBBLED_GABBRO_WALL = REGISTRY.register("cobbled_gabbro_wall", () -> new CobbledGabbroWallBlock());
	public static final RegistryObject<Block> COBBLED_GABBRO_SLAB = REGISTRY.register("cobbled_gabbro_slab", () -> new CobbledGabbroSlabBlock());
	public static final RegistryObject<Block> GABBRO_SLAB = REGISTRY.register("gabbro_slab", () -> new GabbroSlabBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_SLAB = REGISTRY.register("gabbro_bricks_slab", () -> new GabbroBricksSlabBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CRACKED_SLAB = REGISTRY.register("gabbro_bricks_cracked_slab", () -> new GabbroBricksCrackedSlabBlock());
	public static final RegistryObject<Block> GABBRO_TILES_SLAB = REGISTRY.register("gabbro_tiles_slab", () -> new GabbroTilesSlabBlock());
	public static final RegistryObject<Block> GABBRO_TILES_CRACKED_SLAB = REGISTRY.register("gabbro_tiles_cracked_slab", () -> new GabbroTilesCrackedSlabBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_SLAB = REGISTRY.register("gabbro_large_tiles_slab", () -> new GabbroLargeTilesSlabBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_CRACKED_SLAB = REGISTRY.register("gabbro_large_tiles_cracked_slab", () -> new GabbroLargeTilesCrackedSlabBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_SLAB = REGISTRY.register("gabbro_bricks_chiseled_slab", () -> new GabbroBricksChiseledSlabBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_CRACKED_SLAB = REGISTRY.register("gabbro_bricks_chiseled_cracked_slab", () -> new GabbroBricksChiseledCrackedSlabBlock());
	public static final RegistryObject<Block> COBBLED_GABBRO_STAIRS = REGISTRY.register("cobbled_gabbro_stairs", () -> new CobbledGabbroStairsBlock());
	public static final RegistryObject<Block> GABBRO_STAIRS = REGISTRY.register("gabbro_stairs", () -> new GabbroStairsBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_STAIRS = REGISTRY.register("gabbro_bricks_stairs", () -> new GabbroBricksStairsBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CRACKED_STAIRS = REGISTRY.register("gabbro_bricks_cracked_stairs", () -> new GabbroBricksCrackedStairsBlock());
	public static final RegistryObject<Block> GABBRO_TILES_STAIRS = REGISTRY.register("gabbro_tiles_stairs", () -> new GabbroTilesStairsBlock());
	public static final RegistryObject<Block> GABBRO_TILES_CRACKED_STAIRS = REGISTRY.register("gabbro_tiles_cracked_stairs", () -> new GabbroTilesCrackedStairsBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_STAIRS = REGISTRY.register("gabbro_large_tiles_stairs", () -> new GabbroLargeTilesStairsBlock());
	public static final RegistryObject<Block> GABBRO_LARGE_TILES_CRACKED_STAIRS = REGISTRY.register("gabbro_large_tiles_cracked_stairs", () -> new GabbroLargeTilesCrackedStairsBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_STAIRS = REGISTRY.register("gabbro_bricks_chiseled_stairs", () -> new GabbroBricksChiseledStairsBlock());
	public static final RegistryObject<Block> GABBRO_BRICKS_CHISELED_CRACKED_STAIRS = REGISTRY.register("gabbro_bricks_chiseled_cracked_stairs", () -> new GabbroBricksChiseledCrackedStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE = REGISTRY.register("ignimbrite", () -> new IgnimbriteBlock());
	public static final RegistryObject<Block> COBBLED_IGNIMBRITE = REGISTRY.register("cobbled_ignimbrite", () -> new CobbledIgnimbriteBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS = REGISTRY.register("ignimbrite_bricks", () -> new IgnimbriteBricksBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CRACKED = REGISTRY.register("ignimbrite_bricks_cracked", () -> new IgnimbriteBricksCrackedBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_SLAB = REGISTRY.register("ignimbrite_bricks_slab", () -> new IgnimbriteBricksSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CRACKED_SLAB = REGISTRY.register("ignimbrite_bricks_cracked_slab", () -> new IgnimbriteBricksCrackedSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED = REGISTRY.register("ignimbrite_bricks_chiseled", () -> new IgnimbriteBricksChiseledBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_CRACKED = REGISTRY.register("ignimbrite_bricks_chiseled_cracked", () -> new IgnimbriteBricksChiseledCrackedBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_SLAB = REGISTRY.register("ignimbrite_bricks_chiseled_slab", () -> new IgnimbriteBricksChiseledSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_CRACKED_SLAB = REGISTRY.register("ignimbrite_bricks_chiseled_cracked_slab", () -> new IgnimbriteBricksChiseledCrackedSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_STAIRS = REGISTRY.register("ignimbrite_bricks_chiseled_stairs", () -> new IgnimbriteBricksChiseledStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_CRACKED_STAIRS = REGISTRY.register("ignimbrite_bricks_chiseled_cracked_stairs", () -> new IgnimbriteBricksChiseledCrackedStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_WALL = REGISTRY.register("ignimbrite_bricks_chiseled_wall", () -> new IgnimbriteBricksChiseledWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CHISELED_CRACKED_WALL = REGISTRY.register("ignimbrite_bricks_chiseled_cracked_wall", () -> new IgnimbriteBricksChiseledCrackedWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_STAIRS = REGISTRY.register("ignimbrite_bricks_stairs", () -> new IgnimbriteBricksStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CRACKED_STAIRS = REGISTRY.register("ignimbrite_bricks_cracked_stairs", () -> new IgnimbriteBricksCrackedStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_WALL = REGISTRY.register("ignimbrite_bricks_wall", () -> new IgnimbriteBricksWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_BRICKS_CRACKED_WALL = REGISTRY.register("ignimbrite_bricks_cracked_wall", () -> new IgnimbriteBricksCrackedWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES = REGISTRY.register("ignimbrite_tiles", () -> new IgnimbriteTilesBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_CRACKED = REGISTRY.register("ignimbrite_tiles_cracked", () -> new IgnimbriteTilesCrackedBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_SLAB = REGISTRY.register("ignimbrite_tiles_slab", () -> new IgnimbriteTilesSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_STAIRS = REGISTRY.register("ignimbrite_tiles_stairs", () -> new IgnimbriteTilesStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_WALL = REGISTRY.register("ignimbrite_tiles_wall", () -> new IgnimbriteTilesWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_CRACKED_SLAB = REGISTRY.register("ignimbrite_tiles_cracked_slab", () -> new IgnimbriteTilesCrackedSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_CRACKED_STAIRS = REGISTRY.register("ignimbrite_tiles_cracked_stairs", () -> new IgnimbriteTilesCrackedStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_TILES_CRACKED_WALL = REGISTRY.register("ignimbrite_tiles_cracked_wall", () -> new IgnimbriteTilesCrackedWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES = REGISTRY.register("ignimbrite_large_tiles", () -> new IgnimbriteLargeTilesBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_CRACKED = REGISTRY.register("ignimbrite_large_tiles_cracked", () -> new IgnimbriteLargeTilesCrackedBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_SLAB = REGISTRY.register("ignimbrite_large_tiles_slab", () -> new IgnimbriteLargeTilesSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_STAIRS = REGISTRY.register("ignimbrite_large_tiles_stairs", () -> new IgnimbriteLargeTilesStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_WALL = REGISTRY.register("ignimbrite_large_tiles_wall", () -> new IgnimbriteLargeTilesWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_CRACKED_SLAB = REGISTRY.register("ignimbrite_large_tiles_cracked_slab", () -> new IgnimbriteLargeTilesCrackedSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_CRACKED_STAIRS = REGISTRY.register("ignimbrite_large_tiles_cracked_stairs", () -> new IgnimbriteLargeTilesCrackedStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_LARGE_TILES_CRACKED_WALL = REGISTRY.register("ignimbrite_large_tiles_cracked_wall", () -> new IgnimbriteLargeTilesCrackedWallBlock());
	public static final RegistryObject<Block> COBBLED_IGNIMBRITE_SLAB = REGISTRY.register("cobbled_ignimbrite_slab", () -> new CobbledIgnimbriteSlabBlock());
	public static final RegistryObject<Block> COBBLED_IGNIMBRITE_STAIRS = REGISTRY.register("cobbled_ignimbrite_stairs", () -> new CobbledIgnimbriteStairsBlock());
	public static final RegistryObject<Block> COBBLED_IGNIMBRITE_WALL = REGISTRY.register("cobbled_ignimbrite_wall", () -> new CobbledIgnimbriteWallBlock());
	public static final RegistryObject<Block> IGNIMBRITE_SLAB = REGISTRY.register("ignimbrite_slab", () -> new IgnimbriteSlabBlock());
	public static final RegistryObject<Block> IGNIMBRITE_STAIRS = REGISTRY.register("ignimbrite_stairs", () -> new IgnimbriteStairsBlock());
	public static final RegistryObject<Block> IGNIMBRITE_WALL = REGISTRY.register("ignimbrite_wall", () -> new IgnimbriteWallBlock());
	public static final RegistryObject<Block> SYENITE = REGISTRY.register("syenite", () -> new SyeniteBlock());
	public static final RegistryObject<Block> COBBLED_SYENITE = REGISTRY.register("cobbled_syenite", () -> new CobbledSyeniteBlock());
	public static final RegistryObject<Block> COBBLED_SYENITE_SLAB = REGISTRY.register("cobbled_syenite_slab", () -> new CobbledSyeniteSlabBlock());
	public static final RegistryObject<Block> COBBLED_SYENITE_STAIRS = REGISTRY.register("cobbled_syenite_stairs", () -> new CobbledSyeniteStairsBlock());
	public static final RegistryObject<Block> COBBLED_SYENITE_WALL = REGISTRY.register("cobbled_syenite_wall", () -> new CobbledSyeniteWallBlock());
	public static final RegistryObject<Block> SYENITE_SLAB = REGISTRY.register("syenite_slab", () -> new SyeniteSlabBlock());
	public static final RegistryObject<Block> SYENITE_STAIRS = REGISTRY.register("syenite_stairs", () -> new SyeniteStairsBlock());
	public static final RegistryObject<Block> SYENITE_WALL = REGISTRY.register("syenite_wall", () -> new SyeniteWallBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS = REGISTRY.register("syenite_bricks", () -> new SyeniteBricksBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_SLAB = REGISTRY.register("syenite_bricks_slab", () -> new SyeniteBricksSlabBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_STAIRS = REGISTRY.register("syenite_bricks_stairs", () -> new SyeniteBricksStairsBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_WALL = REGISTRY.register("syenite_bricks_wall", () -> new SyeniteBricksWallBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CRACKED = REGISTRY.register("syenite_bricks_cracked", () -> new SyeniteBricksCrackedBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CRACKED_SLAB = REGISTRY.register("syenite_bricks_cracked_slab", () -> new SyeniteBricksCrackedSlabBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CRACKED_STAIRS = REGISTRY.register("syenite_bricks_cracked_stairs", () -> new SyeniteBricksCrackedStairsBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CRACKED_WALL = REGISTRY.register("syenite_bricks_cracked_wall", () -> new SyeniteBricksCrackedWallBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED = REGISTRY.register("syenite_bricks_chiseled", () -> new SyeniteBricksChiseledBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_SLAB = REGISTRY.register("syenite_bricks_chiseled_slab", () -> new SyeniteBricksChiseledSlabBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_STAIRS = REGISTRY.register("syenite_bricks_chiseled_stairs", () -> new SyeniteBricksChiseledStairsBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_WALL = REGISTRY.register("syenite_bricks_chiseled_wall", () -> new SyeniteBricksChiseledWallBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_CRACKED = REGISTRY.register("syenite_bricks_chiseled_cracked", () -> new SyeniteBricksChiseledCrackedBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_CRACKED_SLAB = REGISTRY.register("syenite_bricks_chiseled_cracked_slab", () -> new SyeniteBricksChiseledCrackedSlabBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_CRACKED_STAIRS = REGISTRY.register("syenite_bricks_chiseled_cracked_stairs", () -> new SyeniteBricksChiseledCrackedStairsBlock());
	public static final RegistryObject<Block> SYENITE_BRICKS_CHISELED_CRACKED_WALL = REGISTRY.register("syenite_bricks_chiseled_cracked_wall", () -> new SyeniteBricksChiseledCrackedWallBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES = REGISTRY.register("syenite_large_tiles", () -> new SyeniteLargeTilesBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_SLAB = REGISTRY.register("syenite_large_tiles_slab", () -> new SyeniteLargeTilesSlabBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_STAIRS = REGISTRY.register("syenite_large_tiles_stairs", () -> new SyeniteLargeTilesStairsBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_WALL = REGISTRY.register("syenite_large_tiles_wall", () -> new SyeniteLargeTilesWallBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_CRACKED = REGISTRY.register("syenite_large_tiles_cracked", () -> new SyeniteLargeTilesCrackedBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_CRACKED_SLAB = REGISTRY.register("syenite_large_tiles_cracked_slab", () -> new SyeniteLargeTilesCrackedSlabBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_CRACKED_STAIRS = REGISTRY.register("syenite_large_tiles_cracked_stairs", () -> new SyeniteLargeTilesCrackedStairsBlock());
	public static final RegistryObject<Block> SYENITE_LARGE_TILES_CRACKED_WALL = REGISTRY.register("syenite_large_tiles_cracked_wall", () -> new SyeniteLargeTilesCrackedWallBlock());
	public static final RegistryObject<Block> SYENITE_TILES = REGISTRY.register("syenite_tiles", () -> new SyeniteTilesBlock());
	public static final RegistryObject<Block> SYENITE_TILES_SLAB = REGISTRY.register("syenite_tiles_slab", () -> new SyeniteTilesSlabBlock());
	public static final RegistryObject<Block> SYENITE_TILES_STAIRS = REGISTRY.register("syenite_tiles_stairs", () -> new SyeniteTilesStairsBlock());
	public static final RegistryObject<Block> SYENITE_TILES_WALL = REGISTRY.register("syenite_tiles_wall", () -> new SyeniteTilesWallBlock());
	public static final RegistryObject<Block> SYENITE_TILES_CRACKED = REGISTRY.register("syenite_tiles_cracked", () -> new SyeniteTilesCrackedBlock());
	public static final RegistryObject<Block> SYENITE_TILES_CRACKED_SLAB = REGISTRY.register("syenite_tiles_cracked_slab", () -> new SyeniteTilesCrackedSlabBlock());
	public static final RegistryObject<Block> SYENITE_TILES_CRACKED_STAIRS = REGISTRY.register("syenite_tiles_cracked_stairs", () -> new SyeniteTilesCrackedStairsBlock());
	public static final RegistryObject<Block> SYENITE_TILES_CRACKED_WALL = REGISTRY.register("syenite_tiles_cracked_wall", () -> new SyeniteTilesCrackedWallBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS = REGISTRY.register("locked_bricks", () -> new LockedBricksBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_EMERALD = REGISTRY.register("locked_bricks_emerald", () -> new LockedBricksEmeraldBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_LAPIS = REGISTRY.register("locked_bricks_lapis", () -> new LockedBricksLapisBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_TOPAZ = REGISTRY.register("locked_bricks_topaz", () -> new LockedBricksTopazBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_AMETHYST = REGISTRY.register("locked_bricks_amethyst", () -> new LockedBricksAmethystBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_DIAMOND = REGISTRY.register("locked_bricks_diamond", () -> new LockedBricksDiamondBlock());
	public static final RegistryObject<Block> LOCKED_BRICKS_RUBY = REGISTRY.register("locked_bricks_ruby", () -> new LockedBricksRubyBlock());
	public static final RegistryObject<Block> NETHER_ISLES_RUINED_PORTAL = REGISTRY.register("nether_isles_ruined_portal", () -> new NetherIslesRuinedPortalBlock());
	public static final RegistryObject<Block> BLACKSHROOM_CAP = REGISTRY.register("blackshroom_cap", () -> new BlackshroomCapBlock());
	public static final RegistryObject<Block> BLACKSHROOM_CAP_GLOWING = REGISTRY.register("blackshroom_cap_glowing", () -> new BlackshroomCapGlowingBlock());
	public static final RegistryObject<Block> WHITESHROOM_CAP = REGISTRY.register("whiteshroom_cap", () -> new WhiteshroomCapBlock());
	public static final RegistryObject<Block> WHITESHROOM_CAP_GLOWING = REGISTRY.register("whiteshroom_cap_glowing", () -> new WhiteshroomCapGlowingBlock());
	public static final RegistryObject<Block> DEFINED_VOID_PORTAL = REGISTRY.register("defined_void_portal", () -> new DefinedVoidPortalBlock());
	public static final RegistryObject<Block> URANIUM_ORE = REGISTRY.register("uranium_ore", () -> new UraniumOreBlock());
	public static final RegistryObject<Block> AUGMENT_STATION = REGISTRY.register("augment_station", () -> new AugmentStationBlock());
}
