
package net.ddraig.suprememiningdimension.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.ddraig.suprememiningdimension.block.ZincOreBlock;
import net.ddraig.suprememiningdimension.block.ZincBlockBlock;
import net.ddraig.suprememiningdimension.block.UndergroundDimensionPortalBlock;
import net.ddraig.suprememiningdimension.block.TungstenOreBlock;
import net.ddraig.suprememiningdimension.block.TungstenBlockBlock;
import net.ddraig.suprememiningdimension.block.TinOreBlock;
import net.ddraig.suprememiningdimension.block.TinBlockBlock;
import net.ddraig.suprememiningdimension.block.StrangeForestsPortalBlock;
import net.ddraig.suprememiningdimension.block.SphaleriteOreBlock;
import net.ddraig.suprememiningdimension.block.SilverOreBlock;
import net.ddraig.suprememiningdimension.block.SilverBlockBlock;
import net.ddraig.suprememiningdimension.block.ShiftedSandsPortalBlock;
import net.ddraig.suprememiningdimension.block.ShadeStoneBlock;
import net.ddraig.suprememiningdimension.block.ShadeGrassBlock;
import net.ddraig.suprememiningdimension.block.ShadeDirtBlock;
import net.ddraig.suprememiningdimension.block.ShadeCobblestoneBlock;
import net.ddraig.suprememiningdimension.block.RelitLampBlock;
import net.ddraig.suprememiningdimension.block.QuartzOreBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.PurpleshroomCapBlock;
import net.ddraig.suprememiningdimension.block.PlatinumOreBlock;
import net.ddraig.suprememiningdimension.block.PlatinumBlockBlock;
import net.ddraig.suprememiningdimension.block.OlivineSandBlock;
import net.ddraig.suprememiningdimension.block.NickelOreBlock;
import net.ddraig.suprememiningdimension.block.NickelBlockBlock;
import net.ddraig.suprememiningdimension.block.NetherIslandPortalBlock;
import net.ddraig.suprememiningdimension.block.MusicStationBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurpleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkPurpleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkCyanBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlueGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlueBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackWhiteGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackWhiteBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurpleGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackPurpleBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangeGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackOrangeBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkGreenGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackDarkGreenBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackCyanBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlueGlowingBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlueBlock;
import net.ddraig.suprememiningdimension.block.MushroomStalkBlackBlock;
import net.ddraig.suprememiningdimension.block.LightObsidianBricksBlock;
import net.ddraig.suprememiningdimension.block.LeadOreBlock;
import net.ddraig.suprememiningdimension.block.LeadBlockBlock;
import net.ddraig.suprememiningdimension.block.IronReinforcedObsidianBlock;
import net.ddraig.suprememiningdimension.block.HoneyBlock;
import net.ddraig.suprememiningdimension.block.HeatedMagmaBlockBlock;
import net.ddraig.suprememiningdimension.block.GreyshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.GreyshroomCapBlock;
import net.ddraig.suprememiningdimension.block.GoldReinforcedObsidianBlock;
import net.ddraig.suprememiningdimension.block.GhostlyshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.GhostlyshroomCapBlock;
import net.ddraig.suprememiningdimension.block.FalseOverworldDimensionPortalBlock;
import net.ddraig.suprememiningdimension.block.ExtinguishedLampBlock;
import net.ddraig.suprememiningdimension.block.EtchedWoodBlock;
import net.ddraig.suprememiningdimension.block.EnderCavesPortalBlock;
import net.ddraig.suprememiningdimension.block.EndSoilBlock;
import net.ddraig.suprememiningdimension.block.EndGrassBlock;
import net.ddraig.suprememiningdimension.block.DiamondSandBlock;
import net.ddraig.suprememiningdimension.block.DiamondGravelBlock;
import net.ddraig.suprememiningdimension.block.DenseRedstoneOreBlock;
import net.ddraig.suprememiningdimension.block.DenseLapisOreBlock;
import net.ddraig.suprememiningdimension.block.DenseIronOreBlock;
import net.ddraig.suprememiningdimension.block.DenseGoldOreBlock;
import net.ddraig.suprememiningdimension.block.DenseEmeraldOreBlock;
import net.ddraig.suprememiningdimension.block.DenseDiamondOreBlock;
import net.ddraig.suprememiningdimension.block.DenseCopperOreBlock;
import net.ddraig.suprememiningdimension.block.DenseCoalOreBlock;
import net.ddraig.suprememiningdimension.block.DenseAndesiteBlock;
import net.ddraig.suprememiningdimension.block.DeepCavernsPortalBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.CyanshroomCapBlock;
import net.ddraig.suprememiningdimension.block.CobaltOreBlock;
import net.ddraig.suprememiningdimension.block.CobaltBlockBlock;
import net.ddraig.suprememiningdimension.block.CavernsPortalBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapGlowingBlock;
import net.ddraig.suprememiningdimension.block.BlueshroomCapBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodWoodBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodStairsBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodSlabBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodSaplingBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodPressurePlateBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodPlanksBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodLogBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodLeavesBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodFenceGateBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodFenceBlock;
import net.ddraig.suprememiningdimension.block.BlightwoodButtonBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalSolidBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalSmallBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalMediumBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalLargeBlock;
import net.ddraig.suprememiningdimension.block.BenitoiteCrystalBuddingBlock;
import net.ddraig.suprememiningdimension.block.AntimonyOreBlock;
import net.ddraig.suprememiningdimension.block.AntimonyBlockBlock;
import net.ddraig.suprememiningdimension.block.AncientMossBlock;
import net.ddraig.suprememiningdimension.block.AmberSolidBlock;
import net.ddraig.suprememiningdimension.block.AluminumOreBlock;
import net.ddraig.suprememiningdimension.block.AluminumBlockBlock;
import net.ddraig.suprememiningdimension.SupremeMiningDimensionMod;

public class SupremeMiningDimensionModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, SupremeMiningDimensionMod.MODID);
	public static final RegistryObject<Block> IRON_REINFORCED_OBSIDIAN = REGISTRY.register("iron_reinforced_obsidian", () -> new IronReinforcedObsidianBlock());
	public static final RegistryObject<Block> FALSE_OVERWORLD_DIMENSION_PORTAL = REGISTRY.register("false_overworld_dimension_portal", () -> new FalseOverworldDimensionPortalBlock());
	public static final RegistryObject<Block> NETHER_ISLAND_PORTAL = REGISTRY.register("nether_island_portal", () -> new NetherIslandPortalBlock());
	public static final RegistryObject<Block> GOLD_REINFORCED_OBSIDIAN = REGISTRY.register("gold_reinforced_obsidian", () -> new GoldReinforcedObsidianBlock());
	public static final RegistryObject<Block> UNDERGROUND_DIMENSION_PORTAL = REGISTRY.register("underground_dimension_portal", () -> new UndergroundDimensionPortalBlock());
	public static final RegistryObject<Block> CAVERNS_PORTAL = REGISTRY.register("caverns_portal", () -> new CavernsPortalBlock());
	public static final RegistryObject<Block> DEEP_CAVERNS_PORTAL = REGISTRY.register("deep_caverns_portal", () -> new DeepCavernsPortalBlock());
	public static final RegistryObject<Block> LIGHT_OBSIDIAN_BRICKS = REGISTRY.register("light_obsidian_bricks", () -> new LightObsidianBricksBlock());
	public static final RegistryObject<Block> ENDER_CAVES_PORTAL = REGISTRY.register("ender_caves_portal", () -> new EnderCavesPortalBlock());
	public static final RegistryObject<Block> ETCHED_WOOD = REGISTRY.register("etched_wood", () -> new EtchedWoodBlock());
	public static final RegistryObject<Block> STRANGE_FORESTS_PORTAL = REGISTRY.register("strange_forests_portal", () -> new StrangeForestsPortalBlock());
	public static final RegistryObject<Block> DENSE_DIAMOND_ORE = REGISTRY.register("dense_diamond_ore", () -> new DenseDiamondOreBlock());
	public static final RegistryObject<Block> DENSE_IRON_ORE = REGISTRY.register("dense_iron_ore", () -> new DenseIronOreBlock());
	public static final RegistryObject<Block> DENSE_REDSTONE_ORE = REGISTRY.register("dense_redstone_ore", () -> new DenseRedstoneOreBlock());
	public static final RegistryObject<Block> DENSE_COPPER_ORE = REGISTRY.register("dense_copper_ore", () -> new DenseCopperOreBlock());
	public static final RegistryObject<Block> DENSE_COAL_ORE = REGISTRY.register("dense_coal_ore", () -> new DenseCoalOreBlock());
	public static final RegistryObject<Block> QUARTZ_ORE = REGISTRY.register("quartz_ore", () -> new QuartzOreBlock());
	public static final RegistryObject<Block> DENSE_LAPIS_ORE = REGISTRY.register("dense_lapis_ore", () -> new DenseLapisOreBlock());
	public static final RegistryObject<Block> DENSE_GOLD_ORE = REGISTRY.register("dense_gold_ore", () -> new DenseGoldOreBlock());
	public static final RegistryObject<Block> EXTINGUISHED_LAMP = REGISTRY.register("extinguished_lamp", () -> new ExtinguishedLampBlock());
	public static final RegistryObject<Block> RELIT_LAMP = REGISTRY.register("relit_lamp", () -> new RelitLampBlock());
	public static final RegistryObject<Block> DENSE_EMERALD_ORE = REGISTRY.register("dense_emerald_ore", () -> new DenseEmeraldOreBlock());
	public static final RegistryObject<Block> SILVER_ORE = REGISTRY.register("silver_ore", () -> new SilverOreBlock());
	public static final RegistryObject<Block> SILVER_BLOCK = REGISTRY.register("silver_block", () -> new SilverBlockBlock());
	public static final RegistryObject<Block> TIN_ORE = REGISTRY.register("tin_ore", () -> new TinOreBlock());
	public static final RegistryObject<Block> TIN_BLOCK = REGISTRY.register("tin_block", () -> new TinBlockBlock());
	public static final RegistryObject<Block> TUNGSTEN_ORE = REGISTRY.register("tungsten_ore", () -> new TungstenOreBlock());
	public static final RegistryObject<Block> TUNGSTEN_BLOCK = REGISTRY.register("tungsten_block", () -> new TungstenBlockBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> LEAD_BLOCK = REGISTRY.register("lead_block", () -> new LeadBlockBlock());
	public static final RegistryObject<Block> DENSE_ANDESITE = REGISTRY.register("dense_andesite", () -> new DenseAndesiteBlock());
	public static final RegistryObject<Block> NICKEL_ORE = REGISTRY.register("nickel_ore", () -> new NickelOreBlock());
	public static final RegistryObject<Block> NICKEL_BLOCK = REGISTRY.register("nickel_block", () -> new NickelBlockBlock());
	public static final RegistryObject<Block> PLATINUM_ORE = REGISTRY.register("platinum_ore", () -> new PlatinumOreBlock());
	public static final RegistryObject<Block> PLATINUM_BLOCK = REGISTRY.register("platinum_block", () -> new PlatinumBlockBlock());
	public static final RegistryObject<Block> ALUMINUM_ORE = REGISTRY.register("aluminum_ore", () -> new AluminumOreBlock());
	public static final RegistryObject<Block> ALUMINUM_BLOCK = REGISTRY.register("aluminum_block", () -> new AluminumBlockBlock());
	public static final RegistryObject<Block> ZINC_ORE = REGISTRY.register("zinc_ore", () -> new ZincOreBlock());
	public static final RegistryObject<Block> ZINC_BLOCK = REGISTRY.register("zinc_block", () -> new ZincBlockBlock());
	public static final RegistryObject<Block> AMBER_SOLID = REGISTRY.register("amber_solid", () -> new AmberSolidBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP = REGISTRY.register("blueshroom_cap", () -> new BlueshroomCapBlock());
	public static final RegistryObject<Block> BLUESHROOM_CAP_GLOWING = REGISTRY.register("blueshroom_cap_glowing", () -> new BlueshroomCapGlowingBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP = REGISTRY.register("cyanshroom_cap", () -> new CyanshroomCapBlock());
	public static final RegistryObject<Block> CYANSHROOM_CAP_GLOWING = REGISTRY.register("cyanshroom_cap_glowing", () -> new CyanshroomCapGlowingBlock());
	public static final RegistryObject<Block> GREYSHROOM_CAP = REGISTRY.register("greyshroom_cap", () -> new GreyshroomCapBlock());
	public static final RegistryObject<Block> GREYSHROOM_CAP_GLOWING = REGISTRY.register("greyshroom_cap_glowing", () -> new GreyshroomCapGlowingBlock());
	public static final RegistryObject<Block> GHOSTLYSHROOM_CAP = REGISTRY.register("ghostlyshroom_cap", () -> new GhostlyshroomCapBlock());
	public static final RegistryObject<Block> GHOSTLYSHROOM_CAP_GLOWING = REGISTRY.register("ghostlyshroom_cap_glowing", () -> new GhostlyshroomCapGlowingBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP = REGISTRY.register("purpleshroom_cap", () -> new PurpleshroomCapBlock());
	public static final RegistryObject<Block> PURPLESHROOM_CAP_GLOWING = REGISTRY.register("purpleshroom_cap_glowing", () -> new PurpleshroomCapGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE = REGISTRY.register("mushroom_stalk_blue", () -> new MushroomStalkBlueBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLUE_GLOWING = REGISTRY.register("mushroom_stalk_blue_glowing", () -> new MushroomStalkBlueGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN = REGISTRY.register("mushroom_stalk_cyan", () -> new MushroomStalkCyanBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_CYAN_GLOWING = REGISTRY.register("mushroom_stalk_cyan_glowing", () -> new MushroomStalkCyanGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN = REGISTRY.register("mushroom_stalk_green", () -> new MushroomStalkGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_green_glowing", () -> new MushroomStalkGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE = REGISTRY.register("mushroom_stalk_purple", () -> new MushroomStalkPurpleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_PURPLE_GLOWING = REGISTRY.register("mushroom_stalk_purple_glowing", () -> new MushroomStalkPurpleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK = REGISTRY.register("mushroom_stalk_black", () -> new MushroomStalkBlackBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GLOWING = REGISTRY.register("mushroom_stalk_black_glowing", () -> new MushroomStalkBlackGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE = REGISTRY.register("mushroom_stalk_black_blue", () -> new MushroomStalkBlackBlueBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_BLUE_GLOWING = REGISTRY.register("mushroom_stalk_black_blue_glowing", () -> new MushroomStalkBlackBlueGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN = REGISTRY.register("mushroom_stalk_black_cyan", () -> new MushroomStalkBlackCyanBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_CYAN_GLOWING = REGISTRY.register("mushroom_stalk_black_cyan_glowing", () -> new MushroomStalkBlackCyanGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARK_GREEN = REGISTRY.register("mushroom_stalk_black_dark_green", () -> new MushroomStalkBlackDarkGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_DARK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_black_dark_green_glowing", () -> new MushroomStalkBlackDarkGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN = REGISTRY.register("mushroom_stalk_black_green", () -> new MushroomStalkBlackGreenBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_GREEN_GLOWING = REGISTRY.register("mushroom_stalk_black_green_glowing", () -> new MushroomStalkBlackGreenGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE = REGISTRY.register("mushroom_stalk_black_orange", () -> new MushroomStalkBlackOrangeBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_ORANGE_GLOWING = REGISTRY.register("mushroom_stalk_black_orange_glowing", () -> new MushroomStalkBlackOrangeGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE = REGISTRY.register("mushroom_stalk_black_purple", () -> new MushroomStalkBlackPurpleBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_PURPLE_GLOWING = REGISTRY.register("mushroom_stalk_black_purple_glowing", () -> new MushroomStalkBlackPurpleGlowingBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_WHITE = REGISTRY.register("mushroom_stalk_black_white", () -> new MushroomStalkBlackWhiteBlock());
	public static final RegistryObject<Block> MUSHROOM_STALK_BLACK_WHITE_GLOWING = REGISTRY.register("mushroom_stalk_black_white_glowing", () -> new MushroomStalkBlackWhiteGlowingBlock());
	public static final RegistryObject<Block> HONEY = REGISTRY.register("honey", () -> new HoneyBlock());
	public static final RegistryObject<Block> MUSIC_STATION = REGISTRY.register("music_station", () -> new MusicStationBlock());
	public static final RegistryObject<Block> ANTIMONY_ORE = REGISTRY.register("antimony_ore", () -> new AntimonyOreBlock());
	public static final RegistryObject<Block> ANTIMONY_BLOCK = REGISTRY.register("antimony_block", () -> new AntimonyBlockBlock());
	public static final RegistryObject<Block> COBALT_ORE = REGISTRY.register("cobalt_ore", () -> new CobaltOreBlock());
	public static final RegistryObject<Block> COBALT_BLOCK = REGISTRY.register("cobalt_block", () -> new CobaltBlockBlock());
	public static final RegistryObject<Block> SPHALERITE_ORE = REGISTRY.register("sphalerite_ore", () -> new SphaleriteOreBlock());
	public static final RegistryObject<Block> DIAMOND_SAND = REGISTRY.register("diamond_sand", () -> new DiamondSandBlock());
	public static final RegistryObject<Block> DIAMOND_GRAVEL = REGISTRY.register("diamond_gravel", () -> new DiamondGravelBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_SMALL = REGISTRY.register("benitoite_crystal_small", () -> new BenitoiteCrystalSmallBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_MEDIUM = REGISTRY.register("benitoite_crystal_medium", () -> new BenitoiteCrystalMediumBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_LARGE = REGISTRY.register("benitoite_crystal_large", () -> new BenitoiteCrystalLargeBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_SOLID = REGISTRY.register("benitoite_crystal_solid", () -> new BenitoiteCrystalSolidBlock());
	public static final RegistryObject<Block> SHADE_COBBLESTONE = REGISTRY.register("shade_cobblestone", () -> new ShadeCobblestoneBlock());
	public static final RegistryObject<Block> SHADE_STONE = REGISTRY.register("shade_stone", () -> new ShadeStoneBlock());
	public static final RegistryObject<Block> SHADE_DIRT = REGISTRY.register("shade_dirt", () -> new ShadeDirtBlock());
	public static final RegistryObject<Block> SHADE_GRASS = REGISTRY.register("shade_grass", () -> new ShadeGrassBlock());
	public static final RegistryObject<Block> BENITOITE_CRYSTAL_BUDDING = REGISTRY.register("benitoite_crystal_budding", () -> new BenitoiteCrystalBuddingBlock());
	public static final RegistryObject<Block> ANCIENT_MOSS = REGISTRY.register("ancient_moss", () -> new AncientMossBlock());
	public static final RegistryObject<Block> OLIVINE_SAND = REGISTRY.register("olivine_sand", () -> new OlivineSandBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_WOOD = REGISTRY.register("blightwood_wood", () -> new BlightwoodWoodBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_LOG = REGISTRY.register("blightwood_log", () -> new BlightwoodLogBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_PLANKS = REGISTRY.register("blightwood_planks", () -> new BlightwoodPlanksBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_LEAVES = REGISTRY.register("blightwood_leaves", () -> new BlightwoodLeavesBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_STAIRS = REGISTRY.register("blightwood_stairs", () -> new BlightwoodStairsBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_SLAB = REGISTRY.register("blightwood_slab", () -> new BlightwoodSlabBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_FENCE = REGISTRY.register("blightwood_fence", () -> new BlightwoodFenceBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_FENCE_GATE = REGISTRY.register("blightwood_fence_gate", () -> new BlightwoodFenceGateBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_PRESSURE_PLATE = REGISTRY.register("blightwood_pressure_plate", () -> new BlightwoodPressurePlateBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_BUTTON = REGISTRY.register("blightwood_button", () -> new BlightwoodButtonBlock());
	public static final RegistryObject<Block> BLIGHTWOOD_SAPLING = REGISTRY.register("blightwood_sapling", () -> new BlightwoodSaplingBlock());
	public static final RegistryObject<Block> HEATED_MAGMA_BLOCK = REGISTRY.register("heated_magma_block", () -> new HeatedMagmaBlockBlock());
	public static final RegistryObject<Block> END_SOIL = REGISTRY.register("end_soil", () -> new EndSoilBlock());
	public static final RegistryObject<Block> END_GRASS = REGISTRY.register("end_grass", () -> new EndGrassBlock());
	public static final RegistryObject<Block> SHIFTED_SANDS_PORTAL = REGISTRY.register("shifted_sands_portal", () -> new ShiftedSandsPortalBlock());
}
